# 0 이상의 숫자
# 0 이면 auto-save X
# 1 이상이면  해당 초에 한번씩 저장
# 서버 상태에 맞게 설정
auto-save: 10

# 가상 인벤토리를 저장할 때, 서버에 메시지를 남기는지 true or false
# true면 메시지를 남긴다.
save-messaging: true

# save-messaging == true 일 때, 아래의 메시지를 전송한다.
save-message: "&2[virtual Inventory] 가상 창고가 저장되었습니다."

load-messaging: true

load-message: "&6\t파일 명 : #{fileName}"

# 해당 플러그인은 세이브할 때 미처 변경이 완료 되기 전에
# 저장이 완료되어 일부 데이터 누락이 생길 때를 대비한 기능이다.
# 저장은 변경 이력이 있는 인벤토리만 새롭게 저장한다.
# 변경 이력이 있다고 판단하는 방식은 인벤토리를 생성, 열기 때다.
# 인벤토리를 닫을 때 가상 인벤토리를 식별할 방법이 없다.
# 다음과 같이 열기 -> 인벤 사용1 -> 저장 -> 인벤 사용2 -> 닫기 가 진행되었을 때
# 열기로 인해 인벤 사용1에 대한 점은 변경 이력에 들어가서 저장 시점에 저장되나,
# 저장 이후 인벤 사용 2는 생성, 열기가 진행되지 않기 때문에 플러그인에서 변경점을 저장하지 않는다.
# 결과적으로 사용자들의 아이템 일부가 사라질 수 있다.
# 아래의 변수는 변경점이 등록되지 않아 저장이 되지 않는 인벤토리들을
# 강제로 저장하도록 하는 변수다.
# 변수가 3라는 의미는 저장 O -> 저장 X -> 저장 X -> 저장 X -> 저장 O
# 를 반복하라는 의미로 해석된다.
# 숫자가 너무 낮으면 변경된 적 없는 인벤토리가 계속 저장되어 부담이 될 수 있다.
# 숫자를 너무 높이면 서버에 문제가 생길 때 데이터 손실이 발생할 가능성이 생긴다.
save-once-per-several-times: 3

# 0 이상의 숫자
# 0이면 무한개의 인벤토리 생성 가능(권장하지 않음)
# 1 이상이면 해당 개수를 초과하는 것을 만들 수 없음
# 10개 미만 추천
max-inventory: 10
