name: VirturalInventoryPlugin
version: ${project.version}
main: org.tikim.minecraft.plugin.VirtualInventoryPlugin
api-version: 1.17
authors: [tikim]
description: 가상 인벤토리를 위한 플러그인
website: github.com/xhdtn8070

commands:
  vi:                                            # 명령어 이름
    description: Command for Virtual Inventory   # 명령어 설명
    usage: type '/vi help'

permissions:
  vi.admin:
    description: Admin for virtual Inventory
    default: op

depend:
  - NashornPlus